### ISSUE TITLE
EVM integration

### ISSUE THREAD

**Issue by ryardley** [gnosisguild/enclave#92]
Things to do to get evm integrated. (Note the eth package has been moved to core to avoid circular dependencies until we review the package structure)

- [x] Check that we can receive events and log them #91 
- [x] Get E3id converting from Alloy's Uint<256,4> (need to change it's inner type to be Vec<u8> possibly?) #86 
- [x] Is it possible to convert from generic SolEvent to SpecificEvent? (Seems difficult) possibly with `decode_log`. May require refactor of EVM code to remove abstraction.
- [x] CommitteeRequested converting to events::CommitteeRequested #87 
- [x] CiphernodeAdded converting to events::CiphernodeAdded #88 
- [x] CiphernodeRemoved converting to events::CiphernodeRemoved #89 
- [x] CiphertextOutputPublished converting to events::CiphertextOutputPublished #90 
- [x] Read E3Requested and instantiate within E3RequestManager as context wait for E3Requested before forming committee as we require params in order to form committee
